#!/system/bin/sh
chmod 777 system/etc/init.d/S01defrag

for i in \`busybox find /d* -iname "*.db"\`; do
sqlite3 \$i 'VACUUM;';
echo "  VACUUMED: \$i"
sqlite3 \$i 'REINDEX;';
echo " REINDEXED: \$i"
done

