#!/system/bin/sh
echo "8" > /sys/block/mtdblock0/bdi/read_ahead_kb
echo "8" > /sys/block/mtdblock1/bdi/read_ahead_kb
echo "8" > /sys/block/mtdblock2/bdi/read_ahead_kb
echo "8" > /sys/block/mtdblock3/bdi/read_ahead_kb
echo "128" > /sys/devices/virtual/bdi/7:0/read_ahead_kb
echo "128" > /sys/devices/virtual/bdi/7:1/read_ahead_kb
echo "128" > /sys/devices/virtual/bdi/7:2/read_ahead_kb
echo "128" > /sys/devices/virtual/bdi/7:3/read_ahead_kb
echo "128" > /sys/devices/virtual/bdi/7:4/read_ahead_kb
echo "128" > /sys/devices/virtual/bdi/7:5/read_ahead_kb
echo "128" > /sys/devices/virtual/bdi/7:6/read_ahead_kb
echo "128" > /sys/devices/virtual/bdi/7:7/read_ahead_kb
echo "4096" > /sys/devices/virtual/bdi/179:0/read_ahead_kb
echo "4096" > /sys/devices/virtual/bdi/default/read_ahead_kb
echo "97" > /sys/devices/virtual/bdi/179:0/max_ratio
echo "97" > /sys/devices/virtual/bdi/default/max_ratio
echo "4096" > /sys/devices/virtual/bdi/179:0/read_ahead_kb;
for a in \$LOOP \$MMC
	do
		echo "512" > \$a/queue/nr_requests;
done
