#!/system/bin/sh
chmod -R 777 /sys/class/touch/switch/set_touchscreen;
echo 7035 > /sys/class/touch/switch/set_touchscreen;
echo 8002 > /sys/class/touch/switch/set_touchscreen;
echo 11000 > /sys/class/touch/switch/set_touchscreen;
echo 13060 > /sys/class/touch/switch/set_touchscreen;
echo 14005 > /sys/class/touch/switch/set_touchscreen;
chmod -R 444 /sys/class/touch/switch/set_touchscreen;
