#!/system/bin/sh
# Adrenaline Boost V3
# Brought To You By Imbawind@XDA Developers
clear
echo "=======================";
echo "= Adrenaline Boost V3 =";
echo "=======================";
echo "";
free | awk '/Mem/{print "Free Memory (Before Boost) : "$4" MB";}'
echo "";
echo "";
echo "";
echo -n " Working";
sync;
sleep 1
echo -n ".";
echo "3" > /proc/sys/vm/drop_caches;
sleep 1
echo -n ".";
dc=/proc/sys/vm/drop_caches
dc_v=`cat $dc`
if [ "$dc_v" -gt 1 ]; then
	echo "1" > /proc/sys/vm/drop_caches;
else
	echo " Error When Boosting ! ";
	exit
fi
sleep 1
echo -n ".";
echo "";
sleep 1
echo " [ -=|Adrenaline Boosted|=- ] ";
echo "";
echo "";
echo "";
free | awk '/Mem/{print "Free Memory (After Boost) : "$4" MB";}'
