#!/system/bin/sh
sed -i 's:#OOM (Out-Of-Memory) Groupings' /system/build.prop
sed -i 's:ro.FOREGROUND_APP_MEM=2048:ro.FOREGROUND_APP_MEM=6400:g' /system/build.prop
sed -i 's:ro.VISIBLE_APP_MEM=3584:ro.VISIBLE_APP_MEM=8960:g' /system/build.prop
sed -i 's:ro.SECONDARY_SERVER_MEM=14080:ro.SECONDARY_SERVER_MEM=14080:g' /system/build.prop
sed -i 's:ro.BACKUP_APP_MEM=17920:ro.BACKUP_APP_MEM=17920:g' /system/build.prop
sed -i 's:ro.HOME_APP_MEM=1024:ro.HOME_APP_MEM=3200:g' /system/build.prop
sed -i 's:ro.HIDDEN_APP_MEM=17920:ro.HIDDEN_APP_MEM=17920:g' /system/build.prop
sed -i 's:ro.EMPTY_APP_MEM=25600:ro.EMPTY_APP_MEM=64000:g' /system/build.prop
sed -i 's:ro.PERCEPTIBLE_APP_MEM=1024:ro.PERCEPTIBLE_APP_MEM=3200:g' /system/build.prop
sed -i 's:ro.HEAVY_WEIGHT_APP_MEM=14080:ro.HEAVY_WEIGHT_APP_MEM=14080:g' /system/build.prop
sed -i 's:ro.CONTENT_PROVIDER_MEM=21760:ro.CONTENT_PROVIDER_MEM=38400:g' /system/build.prop
sed -i 's:ro.FOREGROUND_APP_ADJ=8:ro.FOREGROUND_APP_ADJ=25:g' /system/build.prop
sed -i 's:ro.VISIBLE_APP_ADJ=14:ro.VISIBLE_APP_ADJ=35:g' /system/build.prop
sed -i 's:ro.SECONDARY_SERVER_ADJ=55:ro.SECONDARY_SERVER_ADJ=55:g' /system/build.prop
sed -i 's:ro.BACKUP_APP_ADJ=56:ro.BACKUP_APP_ADJ=56:g' /system/build.prop
sed -i 's:ro.HOME_APP_ADJ=9:ro.HOME_APP_ADJ=26:g' /system/build.prop
sed -i 's:ro.EMPTY_APP_ADJ=69:ro.EMPTY_APP_ADJ=69:g' /system/build.prop
sed -i 's:ro.HIDDEN_APP_MIN_ADJ=100:ro.HIDDEN_APP_MIN_ADJ=250:g' /system/build.prop
sed -i 's:ro.PERCEPTIBLE_APP_ADJ=10:ro.PERCEPTIBLE_APP_ADJ=27:g' /system/build.prop
sed -i 's:ro.HEAVY_WEIGHT_APP_ADJ=15:ro.HEAVY_WEIGHT_APP_ADJ=36:g' /system/build.prop
sed -i 's:ro.CONTENT_PROVIDER_ADJ=70:ro.CONTENT_PROVIDER_ADJ=70:g' /system/build.prop
