#!/sbin/sh
# ========================================
# init.d script for Android Revolution HD 
# ========================================

# Enable journal data_writeback for /system, /data and /cache EXT4 partitions

/tmp/tune2fs -o journal_data_writeback $(cat /etc/fstab | grep system | awk '{print $1}')
/tmp/tune2fs -o journal_data_writeback $(cat /etc/fstab | grep data | awk '{print $1}')
/tmp/tune2fs -o journal_data_writeback $(cat /etc/fstab | grep cache | awk '{print $1}')