#!/system/bin/sh
#ThunderBolt!
sync;
sysctl -w vm.drop_caches=3;
#echo 3 > /proc/sys/vm/drop_caches;
sleep 1;
sysctl -w vm.drop_caches=0;
#echo 0 > /proc/sys/vm/drop_caches;
echo "Caches are dropped!";
sysctl -w kernel.sched_min_granularity_ns=200000;
sysctl -w kernel.sched_latency_ns=400000;
sysctl -w kernel.sched_wakeup_granularity_ns=100000;
#echo 200000 > /proc/sys/kernel/sched_min_granularity_ns;
#echo 400000 > /proc/sys/kernel/sched_latency_ns;
#echo 100000 > /proc/sys/kernel/sched_wakeup_granularity_ns;

